feat(ansel-photos): Script improvements
- pictures-import uses $1 as destination
- fuji-x-t-5 is more robust
- instagram-resizer "size" -> "crop", formatting, watermark uses shasum
  of file_name (dependency: shasum), sh -> bash

diff --git a/ansel-photos/.local/scripts/fuji-x-t-5 b/ansel-photos/.local/scripts/fuji-x-t-5
--- a/ansel-photos/.local/scripts/fuji-x-t-5
+++ b/ansel-photos/.local/scripts/fuji-x-t-5
@@ -2,14 +2,37 @@
 
 PATH="$HOME/.local/scripts:$PATH"
 
-sudo mount --mkdir /dev/sdb1 "$HOME/mnt" || exit 1
+if [[ -b "$1" ]]; then
+    echo "Mounting block device '$1' ..."
+    sudo mount --mkdir "$1" "$HOME/mnt" || exit 1
+    echo "Device '$1' mounted successfully"
+else
+    echo "Error: $1 is not a block device" && exit 1
+fi
 
 sources=(
     "$HOME/mnt/dcim/100_fuji"
 )
 
+empty=true
+empty_msg=
+
 for source in "${sources[@]}"; do
-    find "$source" -type f -name *.RAF | pictures-import
+    if ! [[ -d "$source" ]]; then
+        echo "Error: '$source' is not a directory" && exit 1
+    fi
+
+    find "$source" -type f -name *.JPG | pictures-import "$HOME/Pictures/digikam"
+    find "$source" -type f -name *.RAF | pictures-import "$HOME/Pictures/darktable"
+
+    files=$(ls -A "$source")
+    [[ -n "$files" ]] && empty=false
+    empty_msg+="Directory '$source' is $([[ -z "$files" ]] && echo 'empty' || echo 'not empty')\n"
 done
 
-sudo umount "$HOME/mnt"
+printf "$empty_msg"
+echo "Device '$1' is $([[ "$empty" == true ]] && echo 'empty' || echo 'not empty')"
+
+echo "Unmounting block device '$1' ..."
+sudo umount "$HOME/mnt" || exit 1
+echo "Device '$1' unmounted successfully"
diff --git a/ansel-photos/.local/scripts/instagram-resizer b/ansel-photos/.local/scripts/instagram-resizer
--- a/ansel-photos/.local/scripts/instagram-resizer
+++ b/ansel-photos/.local/scripts/instagram-resizer
@@ -1,37 +1,42 @@
-#!/usr/bin/env sh
+#!/usr/bin/env bash
 
 # Produces correctly cropped Instagram photos in the current working directory
 # (non-destructive)
 
-if ! command -v magick &> /dev/null; then
+if ! command -v magick &>/dev/null; then
     echo 'Error: ImageMagick is not installed.'
     exit 1
 fi
 
-if ! command -v exiv2 &> /dev/null; then
+if ! command -v exiv2 &>/dev/null; then
     echo 'Error: Exiv2 is not installed.'
     exit 1
 fi
 
-size="$1"
+if ! command -v shasum &>/dev/null; then
+    echo 'Error: shasum is not installed.'
+    exit 1
+fi
+
+crop="$1"
 
 shift 1
 
-case "$size" in
-    square)
-        width=1080
-        height=$width
-        ;;
-    landscape)
-        width=1080
-        height=810
-        ;;
-    portrait)
-        width=1080
-        height=1350
-        ;;
-    *)
-        echo 'Error: Instagram post size can be square, landscape, or portrait:
+case "$crop" in
+square)
+    width=1080
+    height=$width
+    ;;
+landscape)
+    width=1080
+    height=810
+    ;;
+portrait)
+    width=1080
+    height=1350
+    ;;
+*)
+    echo 'Error: Instagram post crop can be square, landscape, or portrait:
 
 square      1:1   1080x1080
 landscape   4:3   1080x810
@@ -41,9 +46,9 @@ Width of 1080 pixels and aspect ratio between 1.91:1 and 4:5.
 
 https://help.instagram.com/1631821640426723
 
-Usage: ./instagram-resizer <size> <input_image_1> <input_image_2> ...'
-        exit 1
-        ;;
+Usage: ./instagram-resizer <crop> <input_image_1> <input_image_2> ...'
+    exit 1
+    ;;
 esac
 
 border_color=#ffffff
@@ -55,14 +60,15 @@ else
 fi
 
 watermark() {
-    echo "@photatogo  $(date '+%Y%m%d')  $(uuidgen)"
+    file_name_sha1sum=("$(echo -n "${file_name%.*}" | shasum)")
+    echo "@photatogo  $(date '+%Y%m')  ${file_name_sha1sum[0]:0:6}"
 }
 
 hex=${border_color#\#}
 r=$((16#${hex:0:2}))
 g=$((16#${hex:2:2}))
 b=$((16#${hex:4:2}))
-luminance=$(( (r * 2126 + g * 7152 + b * 722) / 10000 ))
+luminance=$(((r * 2126 + g * 7152 + b * 722) / 10000))
 if [ "$luminance" -gt 128 ]; then
     watermark_color=black
 else
@@ -70,22 +76,22 @@ else
 fi
 
 case "$(uname -s)" in
-    Linux)
-        watermark_font="$HOME/.local/share/fonts/UbuntuMonoNerdFontMono-Regular.ttf"
-        ;;
-    Darwin)
-        watermark_font="$HOME/Library/Fonts/UbuntuMonoNerdFontMono-Regular.ttf"
-        ;;
-    *)
-        echo 'Error: Operating system not supported.'
-        exit 1
-        ;;
+Linux)
+    watermark_font="$HOME/.local/share/fonts/UbuntuMonoNerdFontMono-Regular.ttf"
+    ;;
+Darwin)
+    watermark_font="$HOME/Library/Fonts/UbuntuMonoNerdFontMono-Regular.ttf"
+    ;;
+*)
+    echo 'Error: Operating system not supported.'
+    exit 1
+    ;;
 esac
 
 for input_file in "$@"; do
 
     file_name=$(basename "$input_file")
-    dest_file="./${file_name%.*}_$(echo "$size" | tr '[a-z]' '[A-Z]').${file_name##*.}"
+    dest_file="./${file_name%.*}_$(echo "$crop" | tr '[a-z]' '[A-Z]').${file_name##*.}"
 
     if [ -e "$dest_file" ]; then
         echo "Error: File or directory already exists. $dest_file"
diff --git a/ansel-photos/.local/scripts/pictures-import b/ansel-photos/.local/scripts/pictures-import
--- a/ansel-photos/.local/scripts/pictures-import
+++ b/ansel-photos/.local/scripts/pictures-import
@@ -1,6 +1,14 @@
 #!/bin/env bash
 
-dest="$HOME/Pictures/darktable"
+# Never run this script as sudo ($USER will be root)
+
+dest="$1"
+
+compute_hash() {
+    local file=$1
+    local result=($(sha256sum "$file"))
+    echo "${result[0]}"
+}
 
 #######################################
 # Move files and set sensible default permissions and ownership
@@ -13,19 +21,31 @@ move_file_without_permission_and_ownership() {
     local source_file=$1
     local dest_file=$2
 
+    echo "Moving $source_file -> $dest_file"
+
     if [[ "$source_file" == "$dest_file" ]]; then
+        echo "Info: Skipping move. Source and destination paths are identical: $source_file"
         return
+    fi
+
+    if [[ -f "$dest_file" ]]; then
+        if [[ "$(compute_hash "$source_file")" == "$(compute_hash "$dest_file")" ]]; then
+            echo "Info: Skipping move. Source and destination files are identical"
+            return
+        else
+            echo "Error: There is already a different file at the destination with the same name $dest_file"
+            exit 1
+        fi
     fi
 
     # Ensure destination directory exists
     mkdir -p "$(dirname "$dest_file")" || {
-        echo 'Error: could not create destination directory'
+        echo 'Error: Could not create destination directory'
         exit 1
     }
 
-    echo "Moving $source_file -> $dest_file"
     sudo mv --update=none-fail "$source_file" "$dest_file" || {
-        echo 'Error: a file would be replaced in the destination'
+        echo 'Error: Could not move file'
         exit 1
     }
 
@@ -33,33 +53,46 @@ move_file_without_permission_and_ownership() {
     sudo chmod 644 "$dest_file" || exit 1
 }
 
+max_parallel_jobs=5
+current_jobs=0
+
 while IFS= read -r source_file; do
-    # Extract capture time from EXIF metadata
-    capture_time=$({
-        capture_time_array=($(exiv2 -q -Qm -Pkt "$source_file" | grep "Exif.\(Photo\|Image\).DateTimeOriginal[[:space:]]\+"))
-        capture_time="${capture_time_array[1]//:/}"
-        if [[ -n "$capture_time" ]]; then
-            echo "${capture_time%??}"
-        else
-            echo 'unknown'
-        fi
-    })
+    (
+        # Extract capture time from EXIF metadata
+        capture_time=$({
+            capture_time_array=($(exiv2 -q -Qm -Pkt "$source_file" | grep "Exif.\(Photo\|Image\).DateTimeOriginal[[:space:]]\+"))
+            capture_time="${capture_time_array[1]//:/}"
+            if [[ -n "$capture_time" ]]; then
+                echo "${capture_time%??}"
+            else
+                echo 'unknown'
+            fi
+        })
 
-    # Move the main image file
-    file_name=$(basename "$source_file")
-    dest_file="$dest/$capture_time/$file_name"
-    move_file_without_permission_and_ownership "$source_file" "$dest_file" || exit 1
+        # Move the main image file
+        file_name=$(basename "$source_file")
+        dest_file="$dest/$capture_time/$file_name"
+        move_file_without_permission_and_ownership "$source_file" "$dest_file" || exit 1
 
-    # Move any sidecar file(s)
-    sidecar_patterns=(
-        "^.*/${file_name}.xmp$"                                # match base name sidecar (photo.xmp)
-        "^.*/${file_name%.*}_[0-9][0-9].${file_name##*.}.xmp$" # match numbered sidecars (photo_01.xmp, photo_02.xmp, etc.)
-    )
-    source=$(dirname "$source_file")
-    for sidecar_pattern in "${sidecar_patterns[@]}"; do
-        find "$source" -maxdepth 1 -type f -regex "$sidecar_pattern" | while IFS= read -r source_sidecar_file; do
-            dest_sidecar_file="$dest/$capture_time/$(basename "$source_sidecar_file")"
-            move_file_without_permission_and_ownership "$source_sidecar_file" "$dest_sidecar_file" || exit 1
+        # Move any sidecar file(s)
+        sidecar_patterns=(
+            "^.*/${file_name}.xmp$"                                # match base name sidecar (photo.xmp)
+            "^.*/${file_name%.*}_[0-9][0-9].${file_name##*.}.xmp$" # match numbered sidecars (photo_01.xmp, photo_02.xmp, etc.)
+        )
+        source=$(dirname "$source_file")
+        for sidecar_pattern in "${sidecar_patterns[@]}"; do
+            find "$source" -maxdepth 1 -type f -regex "$sidecar_pattern" | while IFS= read -r source_sidecar_file; do
+                dest_sidecar_file="$dest/$capture_time/$(basename "$source_sidecar_file")"
+                move_file_without_permission_and_ownership "$source_sidecar_file" "$dest_sidecar_file" || exit 1
+            done
         done
-    done
+    ) &
+
+    ((current_jobs++))
+    if ((current_jobs >= max_parallel_jobs)); then
+        wait -n
+        ((current_jobs--))
+    fi
 done
+
+wait
